title: Frankiie's Corner
markdown: kramdown

# for atom feed
# author:
#   name: Sharad Raj Singh Maurya
#   email: dev_sharad@outlook.com
# encoding: UTF-8

# gems:
#   - jekyll-paginate-v2

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
    # permalink: /:path

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
# Explicitly turn off the old code
# paginate: nil
# paginate_path: nil
# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 3
#   offset: 2
#   permalink: "/page/:num/"
#   title: ":title - page :num of :max"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true
